{% set version = "0.12.1" %}

package:
  name: cyclonedx-python-lib
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/c/cyclonedx-python-lib/cyclonedx-python-lib-{{ version }}.tar.gz
    sha256: a58b54b1901ab79e78e64e1dcb78401119334fcc8a6f241f1838cde461c2dca5
  - folder: src
    url: https://github.com/CycloneDX/cyclonedx-python-lib/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 8fd8af419cf856c490f7aedd1fde4e2eedb165180f7c26562b69daa591506e22

build:
  number: 0
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6,<4.0
  run:
    - importlib-metadata >=3.4.0,<4.9
    - packageurl-python >=0.3.0,<0.10.0
    - python >=3.6
    - requirements-parser >=0.2.0,<0.3.0
    - setuptools >=47.0.0,<59.3
    - toml >=0.10,<0.11.0
    - types-setuptools >=57.0.0,<57.5
    - types-toml >=0.10.0,<0.11.0
    - typing-extensions >=3.10,<4

test:
  source_files:
    - src/tests
  imports:
    - cyclonedx
  commands:
    - pip check
    - cd src/tests
    - pytest -vv --cov cyclonedx --cov-fail-under 92 --cov-report term-missing:skip-covered --no-cov-on-fail
  requires:
    - pip
    - pytest-cov
    - tox

about:
  home: https://github.com/CycloneDX/cyclonedx-python-lib
  summary: A library for producing CycloneDX SBOM (Software Bill of Materials) files.
  license: Apache-2.0
  license_file: dist/LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
