{% set version = "2.4.0" %}

package:
  name: cyclonedx-python-lib
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/c/cyclonedx-python-lib/cyclonedx-python-lib-{{ version }}.tar.gz
    sha256: 35ef1dbff4aab8ef143552cecde4ef9050f805957519339991e488f80cab36e2
  - folder: src
    url: https://github.com/CycloneDX/cyclonedx-python-lib/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 4bbe5a33d15f63cb3e08a263061e8d5ea2c171c00ca745b3d2dd15ae627228bc

build:
  number: 0
  noarch: python
  script:
    - cd dist && {{ PYTHON }} -m pip install . -vv
    - |-
      {{ PYTHON }} -c "(__import__('pathlib').Path(__import__('site').getsitepackages()[0]) / 'LICENSE').unlink()"

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6
  run:
    - python >=3.6
    # from poetry-generated setup.py
    - packageurl-python >=0.9
    - setuptools >=47.0.0
    - toml >=0.10.0,<0.11.0
    - types-setuptools >=57.0.0
    - types-toml >=0.10.0,<0.11.0
    # :python_version < "3.8"
    - importlib-metadata >=3.4
    - typing_extensions >=3.10,<4.0

test:
  source_files:
    - src/tests
    - src/cyclonedx/schema
  imports:
    - cyclonedx
  commands:
    # more in run_test.py
    - pip check
  requires:
    - jsonschema >=4.2.1
    - lxml >=4.7.0
    - pip
    - pytest-cov
    - tox
    - xmldiff

about:
  home: https://github.com/CycloneDX/cyclonedx-python-lib
  summary: A library for producing CycloneDX SBOM (Software Bill of Materials) files.
  license: Apache-2.0
  license_file: dist/LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
