# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "11.4.0"
  python_check_max: "3.14"

recipe:
  name: cyclonedx-python-lib
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/cyclonedx-python-lib/cyclonedx_python_lib-${{ version }}.tar.gz
  sha256: 1de90231a600340cc6a7bacb35fbe97c75241b39788beaa33a0f49bf4afd4e6c

build:
  number: 0
  noarch: python

outputs:
  - package:
      name: cyclonedx-python-lib
    build:
      noarch: python
      script:
        - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
        # avoid regressing on https://github.com/CycloneDX/cyclonedx-python-lib/issues/435
        - |-
          ${{ PYTHON }} -c "assert not (__import__('pathlib').Path(__import__('site').getsitepackages()[0]) / 'LICENSE').exists()"
    requirements:
      host:
        - pip
        - poetry-core >=1.8.1
        - python ${{ python_min }}.*
      run:
        # from poetry-generated setup.py
        - license-expression >=30.0.0,<31.0.0
        - packageurl-python >=0.11,<2
        - py-serializable >=2.1.0,<3
        - python >=${{ python_min }}
        - sortedcontainers >=2.4.0,<3.0.0
        - typing_extensions >=4.6,<5
    tests:
      - python:
          imports: cyclonedx
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*

  - package:
      name: cyclonedx-python-lib-with-json-validation
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("cyclonedx-python-lib", exact=True) }}
        - jsonschema-with-format-nongpl >=4.25,<5.0
        - referencing >=0.28.4
    tests:
      - python:
          imports: cyclonedx
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*

  - package:
      name: cyclonedx-python-lib-with-xml-validation
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("cyclonedx-python-lib", exact=True) }}
        - lxml >=4,<7
    tests:
      - python:
          imports: cyclonedx
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*

  - package:
      name: cyclonedx-python-lib-with-validation
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("cyclonedx-python-lib", exact=True) }}
        - ${{ pin_subpackage("cyclonedx-python-lib-with-json-validation", exact=True) }}
        - ${{ pin_subpackage("cyclonedx-python-lib-with-xml-validation", exact=True) }}
    tests:
      - python:
          imports: cyclonedx
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*
      - files:
          source:
            - pyproject.toml
            - tests/
        requirements:
          run:
            - ddt >=1.7.1,<2.0.0
            - python ${{ python_min }}.*
            - pytest-cov
            - tox
            - xmldiff
        script:
          - pytest -vv --color=yes --tb=long --cov=cyclonedx --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=90

about:
  homepage: https://github.com/CycloneDX/cyclonedx-python-lib
  summary: Python library for CycloneDX
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE

extra:
  feedstock-name: cyclonedx-python-lib
  recipe-maintainers:
    - bollwyvl
